export enum SERVICES {
  BASE = "",
  AUTH = "/auth",
  REGISTER = "/register",
  COURSE = "/classrooms",
  HERO = "/heroes",
  HOME = "/home",
  BLOG = "/blog",
  TEACHER = "/teachers",
  CATEGORY = "/categories",
  PLAN = "/plans",
  ORDER = "/orders",
  PAYMENT = "/payments",
  PROFILE = "/profiles",
  AVATAR = "/avatars",
  NOTIFICATION = "/notifications",
  NOTES = "/notes",
  FAVORITE = "/favorites",
  SEARCH = "/search",
  ACTIVITIES = "/activities",
  ASSIGNED_CLASSROOM = "/assigned-classroom",
  USER = "/user",
}
