export const GAME_DESCRIPTIONS = {
  blackjack: {
    edge: 0.57,
    name: 'Blackjack',
    volatility: 'Low',
    gameplay: 'Slow',
    difficulty: 'Medium',
    maxWin: '3x',
    provider: "Toshi's Dojo",
    providerSlug: 'blackjack',
    link: '/casino/game/blackjack'
  },
  dice: {
    edge: 1,
    name: 'Dice',
    volatility: 'Low',
    gameplay: 'Fast',
    difficulty: 'Easy',
    maxWin: '49.5x',
    provider: "Toshi's Dojo",
    providerSlug: 'dice',
    link: '/casino/game/dice'
  },
  // crash: {
  //   edge: 1,
  //   name: 'Crash',
  //   volatility: 'High',
  //   gameplay: 'Slow',
  //   difficulty: 'Easy',
  //   maxWin: '1,000,000x',
  //   provider: "Toshi's Dojo",
  //   link: '/casino/game/crash'
  // },
  roulette: {
    edge: 2.7,
    name: 'Roulette',
    volatility: 'Medium',
    gameplay: 'Slow',
    difficulty: 'Easy',
    maxWin: '35x',
    provider: "Toshi's Dojo",
    providerSlug: 'roulette',
    link: '/casino/game/roulette'
  },
  plinko: {
    edge: 1,
    name: 'Plinko',
    volatility: 'High',
    gameplay: 'Fast',
    difficulty: 'Easy',
    maxWin: '3000x',
    provider: "Toshi's Dojo",
    providerSlug: 'plinko',
    link: '/casino/game/plinko',
    bgImage: '/assets/images/laonad.webp'
  },
  mines: {
    edge: 1,
    name: 'Mines',
    volatility: 'Medium',
    gameplay: 'Slow',
    difficulty: 'Easy',
    maxWin: '5,000,000x',
    provider: "Toshi's Dojo",
    providerSlug: 'mines',
    link: '/casino/game/mines'
  },
  limbo: {
    edge: 1,
    name: 'Limbo',
    volatility: 'Medium',
    gameplay: 'Fast',
    difficulty: 'Easy',
    maxWin: '100,000x',
    provider: "Toshi's Dojo",
    providerSlug: 'limbo',
    link: '/casino/game/limbo'
  },
  keno: {
    edge: 1,
    name: 'Keno',
    volatility: 'Medium',
    gameplay: 'Medium',
    difficulty: 'Medium',
    maxWin: '1000x',
    provider: "Toshi's Dojo",
    providerSlug: 'keno',
    link: '/casino/game/keno'
  },
  'dojo-dash': {
    edge: 1,
    name: 'Dojo Dash',
    volatility: 'Low',
    gameplay: 'Easy',
    difficulty: 'Medium',
    maxWin: '3,203,384x',
    provider: "Toshi's Dojo",
    providerSlug: 'crosstheroad',
    link: '/casino/game/dojo-dash'
  },
  'deport-dash': {
    edge: 1,
    name: 'Deport Dash',
    volatility: 'Low',
    gameplay: 'Easy',
    difficulty: 'Medium',
    maxWin: '3,203,384x',
    provider: "Toshi's Dojo",
    providerSlug: 'toshi-crosstheroad',
    link: '/casino/game/deport-dash'
  },
  'toshi-towers': {
    edge: 2,
    name: 'Toshi Towers',
    volatility: 'High',
    gameplay: 'Slow',
    difficulty: 'Easy',
    maxWin: '6429x',
    provider: "Toshi's Dojo",
    providerSlug: 'dragonstower',
    link: '/casino/game/toshi-towers'
  },
  'video-poker': {
    edge: 1,
    name: 'Video Poker',
    volatility: 'Medium',
    gameplay: 'Slow',
    difficulty: 'Easy',
    maxWin: '800x',
    provider: "Toshi's Dojo",
    providerSlug: 'videopoker',
    link: '/casino/game/video-poker'
  },
  hilo: {
    edge: 1,
    name: 'Hilo',
    volatility: 'Medium',
    gameplay: 'Slow',
    difficulty: 'Easy',
    maxWin: '1000x',
    provider: "Toshi's Dojo",
    providerSlug: 'hilo',
    link: '/casino/game/hilo',
    slug: 'hilo',
    pathname: '/casino/game/hilo'
  },
  wheel: {
    edge: 1,
    name: 'Wheel',
    volatility: 'Medium',
    gameplay: 'Slow',
    difficulty: 'Easy',
    maxWin: '49.5x',
    provider: "Toshi's Dojo",
    providerSlug: 'wheel',
    link: '/casino/game/wheel'
  },
  baccarat: {
    edge: 1,
    name: 'Baccarat',
    volatility: 'Medium',
    gameplay: 'Slow',
    difficulty: 'Easy',
    maxWin: '1000x',
    provider: "Toshi's Dojo",
    providerSlug: 'baccarat',
    link: '/casino/game/baccarat'
  }
} as const;

export const PLINKO_ROWS = [
  { label: '8', value: '8' },
  { label: '9', value: '9' },
  { label: '10', value: '10' },
  { label: '11', value: '11' },
  { label: '12', value: '12' },
  { label: '13', value: '13' },
  { label: '14', value: '14' },
  { label: '15', value: '15' },
  { label: '16', value: '16' }
];

export const PROVIDER_COUNTRIES: Record<string, string[]> = {
  'Evolution Gaming': [
    'Denmark',
    'Finland',
    'France',
    'Germany',
    'Greece',
    'Italy',
    'Japan',
    'Mexico',
    'Netherlands',
    'Portugal',
    'Poland',
    'Spain',
    'Switzerland',
    'Thailand'
  ],
  Live88: [
    'Canada',
    'Denmark',
    'Finland',
    'Sweden',
    'France',
    'Germany',
    'Greece',
    'Italy',
    'Japan',
    'Mexico',
    'Netherlands',
    'Portugal',
    'Poland',
    'Spain',
    'Switzerland',
    'Thailand'
  ],
  OneTouch: [
    'Canada',
    'Denmark',
    'Finland',
    'Sweden',
    'France',
    'Germany',
    'Greece',
    'Italy',
    'Japan',
    'Mexico',
    'Netherlands',
    'Portugal',
    'Poland',
    'Spain',
    'Switzerland',
    'Thailand'
  ],
  'Jade Rabbit': ['Canada', 'Finland', 'Germany', 'Japan', 'Mexico', 'Netherlands', 'Poland', 'Thailand'],
  'Red Rake Gaming': ['Canada', 'Finland', 'Germany', 'Japan', 'Mexico', 'Netherlands', 'Poland', 'Thailand'],
  Wazdan: ['Canada', 'Finland', 'Germany', 'Japan', 'Mexico', 'Switzerland', 'Thailand'],
  Popiplay: [
    'Canada',
    'Finland',
    'Sweden',
    'Germany',
    'Italy',
    'Japan',
    'Mexico',
    'Portugal',
    'Poland',
    'Spain',
    'Switzerland',
    'Thailand'
  ],
  Fantasma: [
    'Canada',
    'Finland',
    'Sweden',
    'France',
    'Germany',
    'Italy',
    'Japan',
    'Mexico',
    'Netherlands',
    'Portugal',
    'Poland',
    'Spain',
    'Switzerland',
    'Thailand'
  ],
  Gamomat: ['Ireland', 'Poland', 'Japan', 'Brazil', 'South Africa'],
  PGSoft: [
    'Canada',
    'Finland',
    'Sweden',
    'France',
    'Germany',
    'Italy',
    'Japan',
    'Mexico',
    'Netherlands',
    'Portugal',
    'Poland',
    'Spain',
    'Switzerland',
    'Thailand'
  ],
  GameArt: ['Canada', 'Finland', 'Germany', 'Japan', 'Mexico', 'Poland', 'Thailand'],
  AvatarUX: [
    'Canada',
    'Denmark',
    'Finland',
    'Sweden',
    'France',
    'Germany',
    'Italy',
    'Japan',
    'Mexico',
    'Netherlands',
    'Portugal',
    'Poland',
    'Spain',
    'Switzerland',
    'Thailand'
  ],
  BetsyGames: [
    'Canada',
    'Denmark',
    'Finland',
    'Sweden',
    'France',
    'Germany',
    'Italy',
    'Japan',
    'Mexico',
    'Netherlands',
    'Portugal',
    'Poland',
    'Spain',
    'Switzerland',
    'Thailand'
  ],
  Marbles: [
    'Canada',
    'Denmark',
    'Finland',
    'Sweden',
    'France',
    'Germany',
    'Italy',
    'Japan',
    'Mexico',
    'Netherlands',
    'Portugal',
    'Poland',
    'Spain',
    'Switzerland',
    'Thailand'
  ],
  'Nolimit City': ['Canada', 'Mexico', 'Germany', 'France', 'Iceland', 'Japan', 'Thailand'],
  'Pragmatic Play': ['Canada', 'Austria', 'Finland', 'Mexico', 'Poland', 'Switzerland', 'Thailand'],
  hacksaw: ['Canada', 'Mexico', 'Germany', 'Italy', 'Switzerland', 'New Zealand', 'Denmark'],
  backseat: ['Canada', 'Mexico', 'Germany', 'Italy', 'Switzerland', 'New Zealand', 'Denmark'],
  bullshark: ['Canada', 'Mexico', 'Germany', 'Italy', 'Switzerland', 'New Zealand', 'Denmark'],
  'Push Gaming': ['Argentina', 'Brazil', 'Croatia', 'Finland', 'Malta', 'Iceland', 'Thailand', 'Vietnam'],
  BGaming: [
    'Canada',
    'Denmark',
    'Finland',
    'New Zealand',
    'Sweden',
    'France',
    'Germany',
    'Greece',
    'Italy',
    'Japan',
    'Mexico',
    'Portugal',
    'Poland',
    'Spain',
    'Switzerland',
    'Thailand'
  ],
  '3Oaks': [
    'Canada',
    'Denmark',
    'Finland',
    'New Zealand',
    'Sweden',
    'France',
    'Germany',
    'Greece',
    'Italy',
    'Japan',
    'Mexico',
    'Portugal',
    'Poland',
    'Spain',
    'Switzerland',
    'Thailand'
  ]
};
