export const PROVIDER_BLOCKED_COUNTRIES: Record<string, string[]> = {
  'evolution gaming': [
    'Denmark',
    'Finland',
    'France',
    'Germany',
    'Greece',
    'Italy',
    'Japan',
    'Mexico',
    'Netherlands',
    'Portugal',
    'Poland',
    'Spain',
    'Switzerland',
    'Thailand'
  ],
  '155.io': [
    'Denmark',
    'Finland',
    'France',
    'Germany',
    'Greece',
    'Italy',
    'Japan',
    'Mexico',
    'Netherlands',
    'Portugal',
    'Poland',
    'Spain',
    'Switzerland',
    'Thailand'
  ],
  live88: [
    'Canada',
    'Denmark',
    'Finland',
    'Sweden',
    'France',
    'Germany',
    'Greece',
    'Italy',
    'Japan',
    'Mexico',
    'Netherlands',
    'Portugal',
    'Poland',
    'Spain',
    'Switzerland',
    'Thailand'
  ],
  onetouch: [
    'Canada',
    'Denmark',
    'Finland',
    'Sweden',
    'France',
    'Germany',
    'Greece',
    'Italy',
    'Japan',
    'Mexico',
    'Netherlands',
    'Portugal',
    'Poland',
    'Spain',
    'Switzerland',
    'Thailand'
  ],
  'jade rabbit': [
    'Canada',
    'Denmark',
    'Finland',
    'Sweden',
    'France',
    'Germany',
    'Greece',
    'Italy',
    'Japan',
    'Mexico',
    'Netherlands',
    'Portugal',
    'Poland',
    'Spain',
    'Switzerland',
    'Thailand'
  ],
  'red rake gaming': ['Canada', 'Finland', 'Germany', 'Greece', 'Japan', 'Mexico', 'Netherlands', 'Poland', 'Thailand'],
  wazdan: ['Canada', 'Finland', 'Germany', 'Greece', 'Japan', 'Mexico', 'Switzerland', 'Thailand'],
  popiplay: [
    'Canada',
    'Finland',
    'Sweden',
    'Germany',
    'Greece',
    'Italy',
    'Japan',
    'Mexico',
    'Portugal',
    'Poland',
    'Spain',
    'Switzerland',
    'Thailand'
  ],
  fantasma: [
    'Canada',
    'Finland',
    'Sweden',
    'France',
    'Germany',
    'Greece',
    'Italy',
    'Japan',
    'Mexico',
    'Netherlands',
    'Portugal',
    'Poland',
    'Spain',
    'Switzerland',
    'Thailand'
  ],
  gamomat: ['Ireland', 'Poland', 'Japan', 'Brazil', 'South Africa'],
  pgsoft: [
    'Canada',
    'Finland',
    'Sweden',
    'France',
    'Germany',
    'Greece',
    'Italy',
    'Japan',
    'Mexico',
    'Netherlands',
    'Portugal',
    'Poland',
    'Spain',
    'Switzerland',
    'Thailand'
  ],
  gameart: ['Canada', 'Finland', 'Germany', 'Greece', 'Japan', 'Mexico', 'Poland', 'Thailand'],
  avatarux: [
    'Canada',
    'Denmark',
    'Finland',
    'Sweden',
    'France',
    'Germany',
    'Greece',
    'Italy',
    'Japan',
    'Mexico',
    'Netherlands',
    'Portugal',
    'Poland',
    'Spain',
    'Switzerland',
    'Thailand'
  ],
  betsygames: [
    'Canada',
    'Denmark',
    'Finland',
    'Sweden',
    'France',
    'Germany',
    'Greece',
    'Italy',
    'Japan',
    'Mexico',
    'Netherlands',
    'Portugal',
    'Poland',
    'Spain',
    'Switzerland',
    'Thailand'
  ],
  marbles: [
    'Canada',
    'Denmark',
    'Finland',
    'Sweden',
    'France',
    'Germany',
    'Greece',
    'Italy',
    'Japan',
    'Mexico',
    'Netherlands',
    'Portugal',
    'Poland',
    'Spain',
    'Switzerland',
    'Thailand'
  ],
  'nolimit city': ['Canada', 'Mexico', 'Germany', 'France', 'Iceland', 'Japan', 'Thailand'],
  'pragmatic play': ['Canada', 'Austria', 'Finland', 'Mexico', 'Poland', 'Switzerland', 'Thailand'],
  hacksaw: ['Canada (Outside of Ontario)', 'Mexico', 'Germany', 'Italy', 'Switzerland', 'New Zealand', 'Denmark'],
  backseat: ['Canada (Outside of Ontario)', 'Mexico', 'Germany', 'Italy', 'Switzerland', 'New Zealand', 'Denmark'],
  bullshark: ['Canada (Outside of Ontario)', 'Mexico', 'Germany', 'Italy', 'Switzerland', 'New Zealand', 'Denmark'],
  'push gaming': ['Argentina', 'Brazil', 'Croatia', 'Finland', 'Malta', 'Iceland', 'Thailand', 'Vietnam'],
  bgaming: [
    'Canada',
    'Denmark',
    'Finland',
    'New Zealand',
    'Sweden',
    'France',
    'Germany',
    'Greece',
    'Italy',
    'Japan',
    'Mexico',
    'Portugal',
    'Poland',
    'Spain',
    'Switzerland',
    'Thailand'
  ],
  '3oaks': [
    'Canada',
    'Denmark',
    'Finland',
    'New Zealand',
    'Sweden',
    'Greece',
    'Italy',
    'Japan',
    'Mexico',
    'Portugal',
    'Poland',
    'Spain',
    'Switzerland',
    'Thailand'
  ]
};

export function getBlockedCountriesForProvider(providerName?: string): string[] | undefined {
  if (!providerName) return undefined;
  const normalize = (v: string) =>
    v.toLowerCase().trim().replace(/\s+/g, ' ').replace(/[’'"]/g, '').replace(/[-_]/g, ' ');

  const normalized = normalize(providerName);
  // direct match
  if (PROVIDER_BLOCKED_COUNTRIES[normalized]) return PROVIDER_BLOCKED_COUNTRIES[normalized];
  // fuzzy includes match
  const key = Object.keys(PROVIDER_BLOCKED_COUNTRIES).find(k => {
    const nk = normalize(k);
    return normalized.includes(nk) || nk.includes(normalized);
  });
  return key ? PROVIDER_BLOCKED_COUNTRIES[key] : undefined;
}
