// Generated by automatic - DO NOT EDIT MANUALLY

const l = {
  '/': () => {
    const i = {
      locales: { _type: 'localeString', en: 'Bitcoin Casino with Crypto Games & Daily Rewards | Toshi.bet' }
    };
    const d = {
      locales: {
        _type: 'localeString',
        en: 'Play at a trusted bitcoin casino with secure crypto payouts, daily rewards, and premium casino games. Toshi.bet is a reliable crypto casino for real money play.'
      }
    };
    const s = {
      title: i,
      description: d,
      images: [
        {
          url: `https://static.toshi.bet/public/toshi-bet-crypto-casino.png`,
          alt: 'Toshi Bet - best no KYC Crypto Casino and Sportsbook thumbnail'
        }
      ]
    };
    return { title: i, description: d, openGraph: s };
  },
  '/casino/challenges': {
    title: {
      locales: { _type: 'localeString', en: 'Casino Challenges – Complete Missions & Unlock Rewards | Toshi.bet' }
    },
    description: {
      locales: {
        _type: 'localeString',
        en: 'Complete casino challenges at Toshi.bet by finishing missions and quests. Enjoy structured casino game challenges and unlock rewards while you play online.'
      }
    }
  },
  '/casino/home': {
    title: {
      locales: { _type: 'localeString', en: 'Online Casino Real Money – Play Crypto & Bitcoin Games | Toshi.bet' }
    },
    description: {
      locales: {
        _type: 'localeString',
        en: '"Play at an online casino for real money with secure crypto payouts, premium casino games, and ongoing rewards. Join a trusted crypto casino at Toshi.bet. "'
      }
    }
  },
  '/casino/home/bonus-buy': {
    title: {
      locales: { _type: 'localeString', en: 'Bonus Buy Slots – Slot Games with Bonus Buy Feature | Toshi.bet' }
    },
    description: {
      locales: {
        _type: 'localeString',
        en: 'Play Bonus Buy Slots at Toshi.bet, featuring top titles like Sweet Bonanza and Wanted Dead or a Wild from trusted providers with secure crypto payouts.'
      }
    }
  },
  '/casino/home/live-casino': {
    title: {
      locales: {
        _type: 'localeString',
        en: 'Online Live Casino – Play Live Dealer Games for Real Money & Rewards | Toshi.bet'
      }
    },
    description: {
      locales: {
        _type: 'localeString',
        en: 'Play at an online live casino with real dealers and secure crypto payouts. Enjoy live blackjack, baccarat, roulette, Lightning Roulette, Crazy Time, and more.'
      }
    }
  },
  '/casino/home/slots': {
    title: {
      locales: { _type: 'localeString', en: 'Real Money Slots – Play Online Slots for Real Money | Toshi.bet' }
    },
    description: {
      locales: {
        _type: 'localeString',
        en: 'Play real money slots with Bitcoin, Solana, and more at Toshi.bet. Discover new slot games, enjoy online slots for real money, and play at a trusted crypto casino.'
      }
    }
  },
  '/casino/home/toshis-dojo': {
    title: { locales: { _type: 'localeString', en: 'Toshi’s Dojo – Provably Fair Crypto Casino Games | Toshi.bet' } },
    description: {
      locales: {
        _type: 'localeString',
        en: 'Play crypto casino house games at Toshi’s Dojo, featuring provably fair originals like Plinko, keno, Crash Game and Chicken Cross the road Game, built for real money play.'
      }
    }
  },
  '/casino/new-releases': {
    title: {
      locales: { _type: 'localeString', en: 'New Slots – Latest Slot Game Releases to Play Online | Toshi.bet' }
    },
    description: {
      locales: {
        _type: 'localeString',
        en: 'Discover new slots at Toshi.bet with the latest slot releases from trusted providers. Play new real money slots, including fresh titles from Pragmatic Play and Hacksaw.'
      }
    }
  },
  '/vip': {
    title: { locales: { _type: 'localeString', en: 'VIP Casino Program – Levels, Rewards & Progression | Toshi.bet' } },
    description: {
      locales: {
        _type: 'localeString',
        en: 'Join Toshi.bet’s VIP Casino Program to unlock exclusive VIP levels, rewards, and a casino loyalty programme as you progress through the ranks.'
      }
    }
  }
};

const interpolate = (str, values) => {
  if (!str) return '';
  const v = values || {};
  return String(str).replace(/\{([a-zA-Z0-9_]+)\}/g, (_, k) => (k in v ? String(v[k]) : `{${k}}`));
};

const pickText = (desc, lang, params) => {
  if (!desc) return '';
  if (typeof desc === 'string') return interpolate(desc, params);
  const locales = desc.locales || {};
  const raw = locales[lang] || locales.en || Object.values(locales)[0] || '';
  const values = { ...(desc.values || {}), ...(params || {}) };
  return interpolate(raw, values);
};

const getCanonical = (obj, lang) => {
  if (!obj) return undefined;
  if (obj.canonicalLocalized && typeof obj.canonicalLocalized === 'object') {
    return obj.canonicalLocalized[lang] || obj.canonical || undefined;
  }
  return obj.canonical;
};

const processOpenGraph = (openGraph, lang, params) => {
  if (!openGraph) return undefined;
  const processed = {};
  if (openGraph.title) {
    processed.title = pickText(openGraph.title, lang, params);
  }
  if (openGraph.description) {
    processed.description = pickText(openGraph.description, lang, params);
  }
  if (openGraph.images && Array.isArray(openGraph.images)) {
    processed.images = openGraph.images.map(img => {
      const processedImg = {};
      if (img.url) {
        processedImg.url = typeof img.url === 'string' ? img.url : interpolate(img.url, params);
      }
      if (img.alt) {
        processedImg.alt = typeof img.alt === 'string' ? img.alt : pickText(img.alt, lang, params);
      }
      return processedImg;
    });
  }
  return processed;
};

export const getMetadata = (route, lang = 'en', params = {}) => {
  const def = l[route];
  let routeParams = params;
  if (route === '/') {
    const baseUrl = params.t || params.baseUrl || params.url;
    if (baseUrl) {
      routeParams = { ...params, t: baseUrl };
    }
  }
  const obj = typeof def === 'function' ? def(routeParams) : def;
  if (!obj) return { title: '', description: '', canonical: undefined, openGraph: undefined };
  const title = pickText(obj.title, lang, params);
  const description = pickText(obj.description, lang, params);
  const canonical = getCanonical(obj, lang);
  const openGraph = processOpenGraph(obj.openGraph, lang, routeParams);
  return { title, description, canonical, openGraph };
};

export { l as s };
